[build]
builder = "NIXPACKS"
buildCommand = "bash build.sh"

[deploy]
startCommand = "gunicorn busSeguro.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --access-logfile - --error-logfile -"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
healthcheckPath = "/"
healthcheckTimeout = 30
